### ISSUE TITLE
ImportError: No module named pygst

### ISSUE THREAD

**Issue by suti3112** [9and3r/mopidy-ttsgpio#7]
My Problem:

->

sudo mopidy
INFO     Starting Mopidy 2.0.0
ERROR    Failed to load extension ttsgpio: No module named pygst
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/ext.py", line 202, in load_extensions
    extension_class = entry_point.load(require=False)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['**name**'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_ttsgpio/**init**.py", line 8, in <module>
    import pygst
ImportError: No module named pygst
INFO     Loading config from builtin defaults
INFO     Loading config from /root/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mpd, http, stream, m3u, softwaremixer, file, musicbox_webclient, websettings, tunein
INFO     Disabled extensions: local
WARNING  Found local configuration errors, the extension has been automatically disabled:
WARNING    local/media_dir must be set.
WARNING  Please fix the extension configuration errors or disable the extensions to silence these messages.
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: TuneInBackend, StreamBackend, M3UBackend, FileBackend
INFO     Audio output set to "autoaudiosink"
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     MPD server running at [::ffff:127.0.0.1]:6600
INFO     HTTP server running at [::ffff:127.0.0.1]:6680
INFO     Starting GLib mainloop

**Comment by ghost** [comment]
Seems that pygst is not installed correctly. I would try to reinstall gstreamer so that pygst gets installed.

**Comment by jodal** [comment]
Mopidy 2.0 doesn't use pygst, but PyGI. The change of Python language binding to GStreamer was a required part of the upgrade from GStreamer 0.10 to 1.x.

As you cannot use pygi and pygst in the same process, it looks like Mopidy-TtsGpio is currently incompatible with Mopidy 2.0.

**Comment by ghost** [comment]
Thanks for the info @jodal 
I will try upgrading to mopidy 2.0 and make Mopidy-TtsGpio compatible with it

**Comment by jodal** [comment]
It should simply be a matter of removing the unused import of pygst in `mopidy_ttsgpio/__init__.py`.
